import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Translations
const translations = {
  EN: {
    // Common
    'search.placeholder': 'Search Mall242...',
    'cart': 'Cart',
    'account': 'Account',
    'signIn': 'Sign In',
    'signOut': 'Sign Out',
    'register': 'Register',
    'orders': 'Orders',
    'wishlist': 'Wishlist',
    'vipRewards': 'VIP Rewards',
    'mysteryDrop': 'Mystery Drop',
    'dreamMall': 'Build Mall',
    'todayDeals': "Today's Deals",
    'sell': 'Sell',
    'aiAssist': 'AI Assist',
    'returns': 'Returns',
    
    // Homepage
    'home.hero.title': 'Welcome to Mall242',
    'home.hero.subtitle': "Bahamas' Premier Digital Mall",
    'home.shopByDept': 'Shop by Department',
    'home.todayDeals': "Today's Deals",
    'home.viewAll': 'View All',
    'home.mysteryDrop': 'Mystery Drop',
    'home.mysteryBrand': '??? Major Brand Coming',
    'home.mysterySignup': 'Sign up to reveal',
    'home.vipTitle': 'Unlock VIP Early Access',
    'home.vipDesc': 'Invite friends to Mall242 and unlock exclusive rewards.',
    'home.getLink': 'Get Your Referral Link',
    
    // Products
    'products.filter': 'Filters',
    'products.sort': 'Sort by',
    'products.featured': 'Featured',
    'products.priceLow': 'Price: Low to High',
    'products.priceHigh': 'Price: High to Low',
    'products.rating': 'Avg. Customer Rating',
    'products.newest': 'Newest Arrivals',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.brand': 'Brand',
    'products.clearFilters': 'Clear All Filters',
    'products.applyFilters': 'Apply Filters',
    'products.noResults': 'No products found',
    'products.addToCart': 'Add to Cart',
    'products.outOfStock': 'Out of Stock',
    'products.inStock': 'In Stock',
    
    // Cart
    'cart.empty': 'Your cart is empty',
    'cart.continue': 'Continue Shopping',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.remove': 'Remove',
    'cart.saveForLater': 'Save for Later',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shippingAddress': 'Shipping Address',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.reviewOrder': 'Review Order',
    'checkout.placeOrder': 'Place Order',
    
    // Account
    'account.dashboard': 'Dashboard',
    'account.profile': 'Profile Information',
    'account.addresses': 'Address Book',
    'account.security': 'Login & Security',
    'account.orders': 'Your Orders',
    'account.referrals': 'Referrals',
    'account.wishlist': 'Wishlist',
    
    // Admin
    'admin.dashboard': 'Admin Dashboard',
    'admin.users': 'User Management',
    'admin.products': 'Product Management',
    'admin.orders': 'Order Management',
    'admin.categories': 'Categories',
    'admin.hero': 'Hero Banner',
    'admin.referrals': 'Referrals',
    'admin.broadcast': 'Broadcast',
    'admin.settings': 'Settings',
  },
  ES: {
    'search.placeholder': 'Buscar en Mall242...',
    'cart': 'Carrito',
    'account': 'Cuenta',
    'signIn': 'Iniciar Sesión',
    'signOut': 'Cerrar Sesión',
    'register': 'Registrarse',
    'orders': 'Pedidos',
    'wishlist': 'Lista de Deseos',
    'vipRewards': 'Recompensas VIP',
    'mysteryDrop': 'Lanzamiento Misterioso',
    'dreamMall': 'Construir Centro',
    'todayDeals': 'Ofertas de Hoy',
    'sell': 'Vender',
    'aiAssist': 'Asistente IA',
    'returns': 'Devoluciones',
    'home.hero.title': 'Bienvenido a Mall242',
    'home.hero.subtitle': 'El Centro Comercial Digital de Bahamas',
    'home.shopByDept': 'Comprar por Departamento',
    'home.todayDeals': 'Ofertas de Hoy',
    'home.viewAll': 'Ver Todo',
    'home.mysteryDrop': 'Lanzamiento Misterioso',
    'home.mysteryBrand': '??? Gran Marca Próximamente',
    'home.mysterySignup': 'Regístrate para revelar',
    'home.vipTitle': 'Desbloquea Acceso VIP Anticipado',
    'home.vipDesc': 'Invita amigos a Mall242 y desbloquea recompensas exclusivas.',
    'home.getLink': 'Obtén tu Enlace de Referencia',
    'products.filter': 'Filtros',
    'products.sort': 'Ordenar por',
    'products.featured': 'Destacados',
    'products.priceLow': 'Precio: Menor a Mayor',
    'products.priceHigh': 'Precio: Mayor a Menor',
    'products.rating': 'Calificación Promedio',
    'products.newest': 'Más Recientes',
    'products.category': 'Categoría',
    'products.price': 'Precio',
    'products.brand': 'Marca',
    'products.clearFilters': 'Limpiar Filtros',
    'products.applyFilters': 'Aplicar Filtros',
    'products.noResults': 'No se encontraron productos',
    'products.addToCart': 'Agregar al Carrito',
    'products.outOfStock': 'Agotado',
    'products.inStock': 'En Stock',
    'cart.empty': 'Tu carrito está vacío',
    'cart.continue': 'Seguir Comprando',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Envío',
    'cart.tax': 'Impuesto',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al Pago',
    'cart.remove': 'Eliminar',
    'cart.saveForLater': 'Guardar para Después',
    'checkout.title': 'Pagar',
    'checkout.shippingAddress': 'Dirección de Envío',
    'checkout.paymentMethod': 'Método de Pago',
    'checkout.reviewOrder': 'Revisar Pedido',
    'checkout.placeOrder': 'Realizar Pedido',
    'account.dashboard': 'Panel de Control',
    'account.profile': 'Información de Perfil',
    'account.addresses': 'Libreta de Direcciones',
    'account.security': 'Inicio de Sesión y Seguridad',
    'account.orders': 'Tus Pedidos',
    'account.referrals': 'Referidos',
    'account.wishlist': 'Lista de Deseos',
    'admin.dashboard': 'Panel de Administración',
    'admin.users': 'Gestión de Usuarios',
    'admin.products': 'Gestión de Productos',
    'admin.orders': 'Gestión de Pedidos',
    'admin.categories': 'Categorías',
    'admin.hero': 'Banner Principal',
    'admin.referrals': 'Referidos',
    'admin.broadcast': 'Transmisión',
    'admin.settings': 'Configuración',
  },
  FR: {
    'search.placeholder': 'Rechercher sur Mall242...',
    'cart': 'Panier',
    'account': 'Compte',
    'signIn': 'Connexion',
    'signOut': 'Déconnexion',
    'register': "S'inscrire",
    'orders': 'Commandes',
    'wishlist': 'Liste de Souhaits',
    'vipRewards': 'Récompenses VIP',
    'mysteryDrop': 'Lancement Mystère',
    'dreamMall': 'Construire un Centre',
    'todayDeals': 'Offres du Jour',
    'sell': 'Vendre',
    'aiAssist': 'Assistant IA',
    'returns': 'Retours',
    'home.hero.title': 'Bienvenue à Mall242',
    'home.hero.subtitle': 'Le Centre Commercial Numérique des Bahamas',
    'home.shopByDept': 'Acheter par Département',
    'home.todayDeals': 'Offres du Jour',
    'home.viewAll': 'Voir Tout',
    'home.mysteryDrop': 'Lancement Mystère',
    'home.mysteryBrand': '??? Grande Marque à Venir',
    'home.mysterySignup': 'Inscrivez-vous pour révéler',
    'home.vipTitle': 'Débloquez l\'Accès VIP Anticipé',
    'home.vipDesc': 'Invitez des amis à Mall242 et débloquez des récompenses exclusives.',
    'home.getLink': 'Obtenez Votre Lien de Parrainage',
    'products.filter': 'Filtres',
    'products.sort': 'Trier par',
    'products.featured': 'En Vedette',
    'products.priceLow': 'Prix: Croissant',
    'products.priceHigh': 'Prix: Décroissant',
    'products.rating': 'Note Moyenne',
    'products.newest': 'Nouveautés',
    'products.category': 'Catégorie',
    'products.price': 'Prix',
    'products.brand': 'Marque',
    'products.clearFilters': 'Effacer les Filtres',
    'products.applyFilters': 'Appliquer les Filtres',
    'products.noResults': 'Aucun produit trouvé',
    'products.addToCart': 'Ajouter au Panier',
    'products.outOfStock': 'Rupture de Stock',
    'products.inStock': 'En Stock',
    'cart.empty': 'Votre panier est vide',
    'cart.continue': 'Continuer vos Achats',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.tax': 'Taxe',
    'cart.total': 'Total',
    'cart.checkout': 'Passer à la Caisse',
    'cart.remove': 'Supprimer',
    'cart.saveForLater': 'Garder pour Plus Tard',
    'checkout.title': 'Paiement',
    'checkout.shippingAddress': 'Adresse de Livraison',
    'checkout.paymentMethod': 'Mode de Paiement',
    'checkout.reviewOrder': 'Vérifier la Commande',
    'checkout.placeOrder': 'Passer la Commande',
    'account.dashboard': 'Tableau de Bord',
    'account.profile': 'Informations du Profil',
    'account.addresses': 'Carnet d\'Adresses',
    'account.security': 'Connexion et Sécurité',
    'account.orders': 'Vos Commandes',
    'account.referrals': 'Parrainages',
    'account.wishlist': 'Liste de Souhaits',
    'admin.dashboard': 'Tableau de Bord Admin',
    'admin.users': 'Gestion des Utilisateurs',
    'admin.products': 'Gestion des Produits',
    'admin.orders': 'Gestion des Commandes',
    'admin.categories': 'Catégories',
    'admin.hero': 'Bannière Principale',
    'admin.referrals': 'Parrainages',
    'admin.broadcast': 'Diffusion',
    'admin.settings': 'Paramètres',
  },
  ZH: {
    'search.placeholder': '搜索Mall242...',
    'cart': '购物车',
    'account': '账户',
    'signIn': '登录',
    'signOut': '退出',
    'register': '注册',
    'orders': '订单',
    'wishlist': '心愿单',
    'vipRewards': 'VIP奖励',
    'mysteryDrop': '神秘发布',
    'dreamMall': '建造商城',
    'todayDeals': '今日优惠',
    'sell': '出售',
    'aiAssist': 'AI助手',
    'returns': '退货',
    'home.hero.title': '欢迎来到Mall242',
    'home.hero.subtitle': '巴哈马首屈一指的数字商城',
    'home.shopByDept': '按部门购物',
    'home.todayDeals': '今日优惠',
    'home.viewAll': '查看全部',
    'home.mysteryDrop': '神秘发布',
    'home.mysteryBrand': '??? 即将推出的大品牌',
    'home.mysterySignup': '注册以揭晓',
    'home.vipTitle': '解锁VIP提前访问',
    'home.vipDesc': '邀请朋友加入Mall242，解锁独家奖励。',
    'home.getLink': '获取您的推荐链接',
    'products.filter': '筛选',
    'products.sort': '排序方式',
    'products.featured': '精选',
    'products.priceLow': '价格：从低到高',
    'products.priceHigh': '价格：从高到低',
    'products.rating': '平均评分',
    'products.newest': '最新上架',
    'products.category': '分类',
    'products.price': '价格',
    'products.brand': '品牌',
    'products.clearFilters': '清除所有筛选',
    'products.applyFilters': '应用筛选',
    'products.noResults': '未找到产品',
    'products.addToCart': '加入购物车',
    'products.outOfStock': '缺货',
    'products.inStock': '有货',
    'cart.empty': '您的购物车是空的',
    'cart.continue': '继续购物',
    'cart.subtotal': '小计',
    'cart.shipping': '运费',
    'cart.tax': '税费',
    'cart.total': '总计',
    'cart.checkout': '去结算',
    'cart.remove': '删除',
    'cart.saveForLater': '稍后购买',
    'checkout.title': '结账',
    'checkout.shippingAddress': '收货地址',
    'checkout.paymentMethod': '支付方式',
    'checkout.reviewOrder': '检查订单',
    'checkout.placeOrder': '提交订单',
    'account.dashboard': '控制面板',
    'account.profile': '个人资料',
    'account.addresses': '地址簿',
    'account.security': '登录与安全',
    'account.orders': '您的订单',
    'account.referrals': '推荐',
    'account.wishlist': '心愿单',
    'admin.dashboard': '管理面板',
    'admin.users': '用户管理',
    'admin.products': '产品管理',
    'admin.orders': '订单管理',
    'admin.categories': '分类管理',
    'admin.hero': '横幅管理',
    'admin.referrals': '推荐管理',
    'admin.broadcast': '广播',
    'admin.settings': '设置',
  },
  PT: {
    'search.placeholder': 'Pesquisar no Mall242...',
    'cart': 'Carrinho',
    'account': 'Conta',
    'signIn': 'Entrar',
    'signOut': 'Sair',
    'register': 'Cadastrar',
    'orders': 'Pedidos',
    'wishlist': 'Lista de Desejos',
    'vipRewards': 'Recompensas VIP',
    'mysteryDrop': 'Lançamento Mistério',
    'dreamMall': 'Construir Shopping',
    'todayDeals': 'Ofertas de Hoje',
    'sell': 'Vender',
    'aiAssist': 'Assistente IA',
    'returns': 'Devoluções',
    'home.hero.title': 'Bem-vindo ao Mall242',
    'home.hero.subtitle': 'O Shopping Digital das Bahamas',
    'home.shopByDept': 'Comprar por Departamento',
    'home.todayDeals': 'Ofertas de Hoje',
    'home.viewAll': 'Ver Todos',
    'home.mysteryDrop': 'Lançamento Mistério',
    'home.mysteryBrand': '??? Grande Marca em Breve',
    'home.mysterySignup': 'Cadastre-se para revelar',
    'home.vipTitle': 'Desbloqueie Acesso VIP Antecipado',
    'home.vipDesc': 'Convide amigos para o Mall242 e desbloqueie recompensas exclusivas.',
    'home.getLink': 'Obtenha seu Link de Indicação',
    'products.filter': 'Filtros',
    'products.sort': 'Ordenar por',
    'products.featured': 'Destaques',
    'products.priceLow': 'Preço: Menor para Maior',
    'products.priceHigh': 'Preço: Maior para Menor',
    'products.rating': 'Avaliação Média',
    'products.newest': 'Mais Recentes',
    'products.category': 'Categoria',
    'products.price': 'Preço',
    'products.brand': 'Marca',
    'products.clearFilters': 'Limpar Filtros',
    'products.applyFilters': 'Aplicar Filtros',
    'products.noResults': 'Nenhum produto encontrado',
    'products.addToCart': 'Adicionar ao Carrinho',
    'products.outOfStock': 'Fora de Estoque',
    'products.inStock': 'Em Estoque',
    'cart.empty': 'Seu carrinho está vazio',
    'cart.continue': 'Continuar Comprando',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Frete',
    'cart.tax': 'Imposto',
    'cart.total': 'Total',
    'cart.checkout': 'Finalizar Compra',
    'cart.remove': 'Remover',
    'cart.saveForLater': 'Salvar para Depois',
    'checkout.title': 'Finalizar',
    'checkout.shippingAddress': 'Endereço de Entrega',
    'checkout.paymentMethod': 'Método de Pagamento',
    'checkout.reviewOrder': 'Revisar Pedido',
    'checkout.placeOrder': 'Fazer Pedido',
    'account.dashboard': 'Painel',
    'account.profile': 'Informações do Perfil',
    'account.addresses': 'Caderno de Endereços',
    'account.security': 'Login e Segurança',
    'account.orders': 'Seus Pedidos',
    'account.referrals': 'Indicações',
    'account.wishlist': 'Lista de Desejos',
    'admin.dashboard': 'Painel Admin',
    'admin.users': 'Gestão de Usuários',
    'admin.products': 'Gestão de Produtos',
    'admin.orders': 'Gestão de Pedidos',
    'admin.categories': 'Categorias',
    'admin.hero': 'Banner Principal',
    'admin.referrals': 'Indicações',
    'admin.broadcast': 'Transmissão',
    'admin.settings': 'Configurações',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved && ['EN', 'ES', 'FR', 'ZH', 'PT'].includes(saved) ? saved : 'EN';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language.toLowerCase();
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};